spring.application.name=spring-ai-integration-openai

# OpenAI API configuration

spring.ai.openai.api-key=${OPENAI_API_KEY}
logging.level.org.springframework.ai.chat.client=DEBUG
logging.level.org.springframework.ai.openai=DEBUG
logging.level.org.springframework.web.client=DEBUG


# MY SQL DB Configuration

spring.datasource.mysql.url=jdbc:mysql://localhost:3306/springai?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.mysql.username=root
spring.datasource.mysql.password=root
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver


# MariaDB Configuration

spring.datasource.mariadb.url=jdbc:mariadb://localhost:3308/springai
spring.datasource.mariadb.username=root
spring.datasource.mariadb.password=mysecret
spring.datasource.mariadb.driver-class-name=org.mariadb.jdbc.Driver

# Vector configuration
spring.ai.vectorstore.mariadb.initialize-schema=true
spring.ai.vectorstore.mariadb.distance-type=COSINE
spring.ai.vectorstore.mariadb.dimension=1536